version: '3.3'
services:
  # Database Connection using the Maria DB Container
  db:
    image: mariadb:10.3.6
    container_name: "mdb"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=agsroot
      - MYSQL_PASSWORD=ags
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "9906:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: mysqld --innodb-flush-method=O_DSYNC
  
  # Container for Flask
  web:
    build: .
    container_name: "flaskapp"
    ports:
      - "5000:5000"
    # volumes:
    #  - .:/code